cli: Refactor js cli to support all contracts + add improvements
certusone/wormhole pull request #1100
Opened 2022-04-21 18:52 UTC by kcsongor

2022-04-22 12:55 UTC, bruce-riley approved these changes

2022-04-22 12:55 UTC, bruce-riley commented
Oh, and I forgot to mention, thank you so much for doing this! It will make my life much easier!

2022-04-22 14:17 UTC, kcsongor commented on clients/js/networks.ts
> +const mainnet = {
Good point - we should really have this stuff in the sdk! Then there's a single source of truth, and both the bridge ui and the cli can use it. I'll open a PR to do it

2022-04-22 14:18 UTC, kcsongor commented on clients/js/evm.ts
> +    let signer = new ethers.Wallet(network.key, provider)
sounds like this function should just take the chain id directly then 🤔

2022-04-27 15:16 UTC, bruce-riley submitted a review, later dismissed

2022-04-27 18:03 UTC, evan-gray requested changes
seems safe given that it's all in clients, and I definitely approve of it all being consolidated. can we support "DEVNET" as a network as well.

2022-05-05 23:11 UTC, evan-gray approved these changes

2022-05-06 00:42 UTC, bruce-riley approved these changes

2022-05-06 00:51 UTC, merged