Initial rough draft
certusone/wormhole pull request #1203
Opened 2022-05-18 20:58 UTC by bruce-riley

Change-Id: Ic2c8b15438162fd097e866f9a0ca1f6adf6a3f55

2022-05-18 21:41 UTC, evan-gray requested changes
This approach is looking really promising!

2022-05-18 21:41 UTC, evan-gray commented on node/pkg/celo/celoimpl.go
> -				sink <- convertNewHeadEventToEth(celoEvent)
We don't need this function down below any more then 🙂

2022-05-18 21:41 UTC, evan-gray commented on node/pkg/ethereum/moonbeamimpl.go
> +	timer := time.NewTimer(1 * time.Millisecond) // Start immediately.
can omit the `1 *` here

2022-05-18 21:41 UTC, evan-gray commented on node/pkg/ethereum/moonbeamimpl.go
> +					blockHash, err := e.getBlockHash(ctx, currentBlockNumber)
this could return a NewBlock

2022-05-18 21:41 UTC, evan-gray commented on node/pkg/ethereum/moonbeamimpl.go
> +					ev, err := e.getBlock(ctx, currentBlockNumber)
If the `getBlockHash` call above instead returned a NewBlock, you could avoid this call.

2022-05-18 21:41 UTC, evan-gray commented on node/pkg/ethereum/moonbeamimpl.go
> +					blockHash, err := e.getBlockHash(ctx, currentBlockNumber)
I feel like there's some small inefficiency between this and the `getLatestBlockNumber` call above, though only the first loop when currentBlockNumber == latestBlockNumber. Not immediately sure how to make it more efficient.

2022-05-18 21:41 UTC, evan-gray commented on node/pkg/ethereum/moonbeamimpl.go
> +func (e *MoonbeamImpl) getBlockHash(ctx context.Context, number uint64) (ethCommon.Hash, error) {
I think there's a way to combine this with `getLatestBlockNumber`, check out https://github.com/ethereum/go-ethereum/blob/440c9fcf75d9d5383b72646a65d5e21fa7ab6a26/ethclient/ethclient.go#L533-L542. Also should number be `*big.Int`?

2022-05-18 21:41 UTC, evan-gray commented on node/pkg/ethereum/moonbeamimpl.go
> +	err := e.mbRpcCon.CallContext(ctx, &m, "eth_getBlockByNumber", strconv.FormatUint(number, 10), false)
you won't need the string conversion with the helper linked above

2022-05-18 21:41 UTC, evan-gray commented on node/pkg/ethereum/moonbeamimpl.go
> +	return strconv.ParseUint(m.Number.String()[2:], 16, 64)
This should probably just return m.Number

2022-05-19 17:49 UTC, SEJeff approved these changes

2022-05-19 17:49 UTC, SEJeff commented on node/pkg/ethereum/moonbeamimpl.go
> +	mbRpcCon *ethRpc.Client
I understand what this is, but `client` seems a bit nicer wrt naming.

2022-05-19 17:49 UTC, SEJeff commented on node/pkg/ethereum/moonbeamimpl.go
> +				timer = time.NewTimer(DELAY_IN_MS * time.Millisecond)
Using a variable for that instead of a magic number. 👍

2022-05-19 17:49 UTC, SEJeff commented on node/pkg/ethereum/moonbeamimpl.go
> +
Might be nice to add a comment somewhere about why `isBlockFinalized` is even necessary. I know why now, but someone new might not understand why.

2022-05-23 07:46 UTC, SEJeff approved these changes

2022-05-23 07:46 UTC, SEJeff commented on node/pkg/ethereum/moonbeamimpl.go
> +// we use a polling mechanism to get the next expected block, and keep doing it until it is marked final.
👍   this is excellent. Thankyou!

2022-06-06 20:34 UTC, SEJeff approved these changes

2022-06-06 20:50 UTC, SEJeff approved these changes

2022-06-07 14:36 UTC, merged