ethereum: Add fromAddress to payload 3
certusone/wormhole pull request #1222
Opened 2022-05-23 22:09 UTC by kcsongor

TODO: fix and add more tests

2022-05-24 03:47 UTC, evan-gray approved these changes

2022-05-24 03:47 UTC, evan-gray requested changes
Looks good, just gotta fix the tests

2022-05-27 17:16 UTC, jumpsiegel commented on whitepapers/0003_token_bridge.md
>  Fee uint256
Why is the fee still here?

2022-05-27 18:34 UTC, kcsongor commented on whitepapers/0003_token_bridge.md
>  Fee uint256
wip

2022-06-22 02:35 UTC, evan-gray approved these changes

2022-06-22 02:35 UTC, merged