solana: Add "msg.sender" and remove fee from payload3
certusone/wormhole pull request #1279
Opened 2022-06-15 21:56 UTC by kcsongor

2022-06-22 18:13 UTC, hendrikhofstadt requested changes

2022-06-22 18:24 UTC, Reisen approved these changes
All good, comments in `instructions.rs` either consistently escaped or neither escaped is the only nitpick I have, the code changes themselves seem :ok_hand:, will re-review the tests.

2022-06-22 18:30 UTC, kcsongor commented on solana/modules/token_bridge/program/src/instructions.rs
> +    let sender = match data.cpi_program_id {
good catch

2022-06-22 18:33 UTC, kcsongor commented on solana/modules/token_bridge/program/src/api/transfer_payload.rs
> +impl<'a, 'b: 'a, 'c> Peel<'a, 'b, 'c> for SenderAccount<'b> {
Yes, it seems to me like having a `Seeded` implementation is the canonical way to signal that a type is a PDA, and didn't want to break away from this pattern. agreed that the `Peel` is a little heavy here, but I think it pays off for consistency

2022-06-28 15:24 UTC, hendrikhofstadt approved these changes

2022-06-30 17:37 UTC, merged