cosmwasm: move chain id and fee denom to storage
certusone/wormhole pull request #1369
Opened 2022-07-18 21:27 UTC by kcsongor

Prior to this change, these values were hardcode in the contract, as
the only supported chain was terra 2. This change allows the contract to
be deployed to other cosmwasm chains without having to recompile the
contract for each one.

The migration code ensures that terra2 is upgraded appropriately.

2022-07-19 02:55 UTC, karlkempe submitted a review, later dismissed
Looks good

2022-07-19 18:15 UTC, evan-gray commented on cosmwasm/contracts/wormhole/src/state.rs
> +    /// The typo is an easter egg.
🐰 🥚 😆

2022-07-20 01:27 UTC, evan-gray requested changes
Looking good, but please remove CHAIN_ID from https://github.com/certusone/wormhole/tree/dev.v2/cosmwasm/contracts/token-bridge/src/lib.rs#L13 and you may find more changes are necessary.

2022-07-20 13:10 UTC, panoel submitted a review, later dismissed

2022-07-20 14:25 UTC, panoel approved these changes

2022-07-20 20:09 UTC, merged