terra/nft_bridge: Implement nft-bridge for terra
certusone/wormhole pull request #698
Opened 2022-01-02 23:51 UTC by kcsongor

**Stack**:
- #697
- #696

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2022-01-03 16:37 UTC, hendrikhofstadt commented
Will wait for the SPL cache

2022-01-04 09:37 UTC, hendrikhofstadt requested changes

2022-01-04 09:37 UTC, hendrikhofstadt commented on terra/contracts/nft-bridge/src/contract.rs
> +                spl_cache(deps.storage).save(&transfer_info.token_id, &spl_cache_item);
result not handled

2022-01-04 09:54 UTC, kcsongor commented on terra/contracts/nft-bridge/src/contract.rs
> +                spl_cache(deps.storage).save(&transfer_info.token_id, &spl_cache_item);
nice catch, very subtle!

2022-01-04 10:17 UTC, hendrikhofstadt approved these changes

2022-01-07 15:47 UTC, merged