Initial Rust SDK
certusone/wormhole pull request #713
Opened 2022-01-04 15:14 UTC by Reisen

This PR contains several commits, each commit is individually reviewable.

2022-01-04 15:54 UTC, kcsongor commented on sdk/rust/core/src/vaa/nft.rs
> +    pub symbol: String,
Aren't `symbol` and `name` supposed to be [u8; 32]? The nft spec says so

2022-01-04 16:00 UTC, kcsongor commented on sdk/rust/sdk/src/chains/terra.rs
> +pub fn post_message<T>(wormhole: Addr, nonce: u32, message: &T) -> StdResult<CosmosMsg>
Why do these functions take the wormhole address as an argument, and not just use `id()` internally?

2022-01-04 16:33 UTC, hendrikhofstadt requested changes
Pls drop the binary .so files

2022-01-05 20:52 UTC, kcsongor commented on sdk/rust/core/src/vaa/nft.rs
> +    pub symbol: String,
On the receiving end, `String` is nicer for sure, but when you construct one of these, I think it's better if the type tells you about the size limitation explicitly as it's an important detail in the spec

2022-01-14 12:29 UTC, hendrikhofstadt approved these changes

2022-01-14 13:09 UTC, merged