Explorer UI
certusone/wormhole pull request #820
Opened 2022-02-07 19:29 UTC by timpau

- brand page
- shapes and gradients
- custom fonts

2022-02-11 14:48 UTC, evan-gray requested changes

2022-02-11 14:48 UTC, evan-gray commented on explorer/src/components/Navbar.tsx
> +          component={RouterLink}
This should be an `OutboundLink` if it goes to an external resource

2022-02-11 14:48 UTC, evan-gray commented on explorer/src/components/Navbar.tsx
> +          to="https://www.immunefi.com/bounty/wormhole/"
This should be `href` if it goes to an external resource

2022-02-11 14:48 UTC, evan-gray commented on explorer/src/components/SEO.tsx
> +import Suisse from '../fonts/SuisseBPIntlBold.woff2'
Fonts should be added in `plugins/gatsby-plugin-top-layout/TopLayout.js`, not here.

2022-02-11 14:48 UTC, evan-gray commented on explorer/src/components/Footer.tsx
> +                href={brand}
This is an internal link so should use `component={RouterLink}` and `to` like the above.

2022-02-11 14:48 UTC, evan-gray commented on explorer/src/components/GridWithCards.tsx
> +            <Typography variant="h4" textAlign={headerTextAlign} dangerouslySetInnerHTML={{__html: header}} />
please do not use `dangerouslySetInnerHTML`

2022-02-23 23:17 UTC, justinschuldt commented
I took the explorer changes from this branch and applied them to a fresh copy of the repo. I'm not sure where all the extra commits came from, or how to make this branch clean. @timpau please check out #902.

2022-02-24 16:33 UTC, timpau commented
> I took the explorer changes from this branch and applied them to a fresh copy of the repo. I'm not sure where all the extra commits came from, or how to make this branch clean. @timpau please check out #902.

yes, i guess something went wrong on that rebase. i can close this ?

2022-02-25 22:43 UTC, closed without merging