bridge_ui: xdefi and leap wallet support
certusone/wormhole pull request #866
Opened 2022-02-16 16:34 UTC by kev1n-peters

2022-02-18 23:43 UTC, evan-gray requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/866)* status: all files reviewed, 8 unresolved discussions (waiting on @chase-45 and @kev1n-peters)

___
*[bridge_ui/src/components/TerraConnectWalletDialog.tsx, line 54 at r1](https://reviewable.io/reviews/certusone/wormhole/866#-MwEBNm19gRNaMKs2FxV:-MwEBNm19gRNaMKs2FxW:b-4o1ns5) ([raw file](https://github.com/certusone/wormhole/blob/4a7feb7aaa034945260efd0a7248ed10a4e94e07/bridge_ui/src/components/TerraConnectWalletDialog.tsx#L54)):*
> ```XML
>       <List>
>         {availableConnections
>           .filter(({ type }) => type !== ConnectType.READONLY)
> ```

probably not a huge difference, but you could do this filtering in a `useMemo`. not sure it'd make too much of a difference given everything is keyed anyway, but this might re-render more often than necessary if you ever refactor since it's always creating a new list.
___
*[bridge_ui/src/components/TerraConnectWalletDialog.tsx, line 59 at r1](https://reviewable.io/reviews/certusone/wormhole/866#-MwECOV36LlfWWjDyt8f:-MwECOV36LlfWWjDyt8g:b-q7f22r) ([raw file](https://github.com/certusone/wormhole/blob/4a7feb7aaa034945260efd0a7248ed10a4e94e07/bridge_ui/src/components/TerraConnectWalletDialog.tsx#L59)):*
> ```XML
>               button
>               key={"connection-" + type + identifier}
>               onClick={() => {
> ```

likely worth making a component for this so that it can leverage a `useCallback`
___
*[bridge_ui/src/components/TerraConnectWalletDialog.tsx, line 72 at r1](https://reviewable.io/reviews/certusone/wormhole/866#-MwEBX9L--R7cyJC0mRN:-MwEBX9L--R7cyJC0mRO:birg1wn) ([raw file](https://github.com/certusone/wormhole/blob/4a7feb7aaa034945260efd0a7248ed10a4e94e07/bridge_ui/src/components/TerraConnectWalletDialog.tsx#L72)):*
> ```XML
>         {availableInstallations
>           .filter(({ type }) => type !== ConnectType.READONLY)
>           .map(({ type, name, icon, url, identifier = "" }) => (
> ```

ditto regarding `useMemo`
___
*[bridge_ui/src/components/TerraWalletKey.tsx, line 15 at r1](https://reviewable.io/reviews/certusone/wormhole/866#-MwEAiSsB1rWy47I040A:-MwEAiSsB1rWy47I040B:ba3gjn5) ([raw file](https://github.com/certusone/wormhole/blob/4a7feb7aaa034945260efd0a7248ed10a4e94e07/bridge_ui/src/components/TerraWalletKey.tsx#L15)):*
> ```XML
>     <>
>       <ToggleConnectedButton
>         connect={() => setIsDialogOpen(true)}
> ```

this will create a new function every time causing a re-render. probably want to do something like



_Code snippet:_
```XML
const connect = useCallback(()=>{setIsDialogOpen(true)},[])
...
connect={connect}
```
___
*[bridge_ui/src/components/TerraWalletKey.tsx, line 16 at r1](https://reviewable.io/reviews/certusone/wormhole/866#-MwEAV3xDBfg1f4YT7od:-MwEAV3xDBfg1f4YT7oe:bewagpw) ([raw file](https://github.com/certusone/wormhole/blob/4a7feb7aaa034945260efd0a7248ed10a4e94e07/bridge_ui/src/components/TerraWalletKey.tsx#L16)):*
> ```XML
>       <ToggleConnectedButton
>         connect={() => setIsDialogOpen(true)}
>         disconnect={() => wallet.disconnect()}
> ```

would this work? 



_Code snippet:_
```XML
disconnect={wallet.disconnect}
```
___
*[bridge_ui/src/components/TerraWalletKey.tsx, line 22 at r1](https://reviewable.io/reviews/certusone/wormhole/866#-MwEB7nrBZShu_6iiUnN:-MwEB7nrBZShu_6iiUnO:b-1c1jpn) ([raw file](https://github.com/certusone/wormhole/blob/4a7feb7aaa034945260efd0a7248ed10a4e94e07/bridge_ui/src/components/TerraWalletKey.tsx#L22)):*
> ```XML
>       <TerraConnectWalletDialog
>         isOpen={isDialogOpen}
>         onClose={() => setIsDialogOpen(false)}
> ```

same as with `connect`
___
*[bridge_ui/src/contexts/TerraWalletContext.tsx, line 17 at r1](https://reviewable.io/reviews/certusone/wormhole/866#-MwECdBnEZ-VhkTARdbP:-MwECdBnEZ-VhkTARdbQ:b-t8wzli) ([raw file](https://github.com/certusone/wormhole/blob/4a7feb7aaa034945260efd0a7248ed10a4e94e07/bridge_ui/src/contexts/TerraWalletContext.tsx#L17)):*
> ```XML
> 
> const walletConnectChainIds: Record<number, NetworkInfo> = {
>   0: testnet,
> ```

not super familiar with how these chainIds work and I get adding testnet, but do we no longer need localnet?
___
*[bridge_ui/src/contexts/TerraWalletContext.tsx, line 28 at r1](https://reviewable.io/reviews/certusone/wormhole/866#-MwECmnJ4EdtWMf3Rotv:-MwECmnJ4EdtWMf3Rotw:b-4iumf) ([raw file](https://github.com/certusone/wormhole/blob/4a7feb7aaa034945260efd0a7248ed10a4e94e07/bridge_ui/src/contexts/TerraWalletContext.tsx#L28)):*
> ```XML
>   return (
>     <WalletProvider
>       defaultNetwork={mainnet}
> ```

should we change the default based on `CLUSTER`?


<!-- Sent from Reviewable.io -->

2022-02-21 21:54 UTC, chase-45 submitted a review, later dismissed

2022-02-23 15:18 UTC, chase-45 approved these changes

2022-02-23 16:56 UTC, kev1n-peters reviewed
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/866)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @evan-gray)

___
*[bridge_ui/src/components/TerraConnectWalletDialog.tsx, line 54 at r1](https://reviewable.io/reviews/certusone/wormhole/866#-MwEBNm19gRNaMKs2FxV:-MwbVl58DRqaQipiLlvs:b-896fix) ([raw file](https://github.com/certusone/wormhole/blob/5e607efcc1e919b0570c7d17271b3ae22c1c372b/bridge_ui/src/components/TerraConnectWalletDialog.tsx#L54)):*
<details><summary><i>Previously, evan-gray (Evan Gray) wrote…</i></summary><blockquote>

probably not a huge difference, but you could do this filtering in a `useMemo`. not sure it'd make too much of a difference given everything is keyed anyway, but this might re-render more often than necessary if you ever refactor since it's always creating a new list.
</blockquote></details>

Done.
___
*[bridge_ui/src/components/TerraConnectWalletDialog.tsx, line 59 at r1](https://reviewable.io/reviews/certusone/wormhole/866#-MwECOV36LlfWWjDyt8f:-MwbVlibEhWLYNg17a9z:b-896fix) ([raw file](https://github.com/certusone/wormhole/blob/5e607efcc1e919b0570c7d17271b3ae22c1c372b/bridge_ui/src/components/TerraConnectWalletDialog.tsx#L59)):*
<details><summary><i>Previously, evan-gray (Evan Gray) wrote…</i></summary><blockquote>

likely worth making a component for this so that it can leverage a `useCallback`
</blockquote></details>

Done.
___
*[bridge_ui/src/components/TerraConnectWalletDialog.tsx, line 72 at r1](https://reviewable.io/reviews/certusone/wormhole/866#-MwEBX9L--R7cyJC0mRN:-MwbVm25EfQ9XI_5i2Rf:b-896fix) ([raw file](https://github.com/certusone/wormhole/blob/5e607efcc1e919b0570c7d17271b3ae22c1c372b/bridge_ui/src/components/TerraConnectWalletDialog.tsx#L72)):*
<details><summary><i>Previously, evan-gray (Evan Gray) wrote…</i></summary><blockquote>

ditto regarding `useMemo`
</blockquote></details>

Done.
___
*[bridge_ui/src/components/TerraWalletKey.tsx, line 15 at r1](https://reviewable.io/reviews/certusone/wormhole/866#-MwEAiSsB1rWy47I040A:-MwbVmeTDEQMsG_wTwQ8:b-896fix) ([raw file](https://github.com/certusone/wormhole/blob/5e607efcc1e919b0570c7d17271b3ae22c1c372b/bridge_ui/src/components/TerraWalletKey.tsx#L15)):*
<details><summary><i>Previously, evan-gray (Evan Gray) wrote…</i></summary><blockquote>

this will create a new function every time causing a re-render. probably want to do something like
</blockquote></details>

Done.
___
*[bridge_ui/src/components/TerraWalletKey.tsx, line 16 at r1](https://reviewable.io/reviews/certusone/wormhole/866#-MwEAV3xDBfg1f4YT7od:-MwbVmyfCyI3K0ZqU6m3:b-896fix) ([raw file](https://github.com/certusone/wormhole/blob/5e607efcc1e919b0570c7d17271b3ae22c1c372b/bridge_ui/src/components/TerraWalletKey.tsx#L16)):*
<details><summary><i>Previously, evan-gray (Evan Gray) wrote…</i></summary><blockquote>

would this work? 
</blockquote></details>

Done.
___
*[bridge_ui/src/components/TerraWalletKey.tsx, line 22 at r1](https://reviewable.io/reviews/certusone/wormhole/866#-MwEB7nrBZShu_6iiUnN:-MwbVnHr7Xb9vnxwjPpq:b-896fix) ([raw file](https://github.com/certusone/wormhole/blob/5e607efcc1e919b0570c7d17271b3ae22c1c372b/bridge_ui/src/components/TerraWalletKey.tsx#L22)):*
<details><summary><i>Previously, evan-gray (Evan Gray) wrote…</i></summary><blockquote>

same as with `connect`
</blockquote></details>

Done.
___
*[bridge_ui/src/contexts/TerraWalletContext.tsx, line 17 at r1](https://reviewable.io/reviews/certusone/wormhole/866#-MwECdBnEZ-VhkTARdbP:-MwbVnlr8R59PiMiPnrB:b-896fix) ([raw file](https://github.com/certusone/wormhole/blob/5e607efcc1e919b0570c7d17271b3ae22c1c372b/bridge_ui/src/contexts/TerraWalletContext.tsx#L17)):*
<details><summary><i>Previously, evan-gray (Evan Gray) wrote…</i></summary><blockquote>

not super familiar with how these chainIds work and I get adding testnet, but do we no longer need localnet?
</blockquote></details>

Done.
___
*[bridge_ui/src/contexts/TerraWalletContext.tsx, line 28 at r1](https://reviewable.io/reviews/certusone/wormhole/866#-MwECmnJ4EdtWMf3Rotv:-MwbVo8_0JqTOGxa5eCH:b-896fix) ([raw file](https://github.com/certusone/wormhole/blob/5e607efcc1e919b0570c7d17271b3ae22c1c372b/bridge_ui/src/contexts/TerraWalletContext.tsx#L28)):*
<details><summary><i>Previously, evan-gray (Evan Gray) wrote…</i></summary><blockquote>

should we change the default based on `CLUSTER`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-24 04:51 UTC, evan-gray approved these changes
> Reviewed 2 of 3 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/866)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kev1n-peters)

___
*[bridge_ui/src/components/TerraConnectWalletDialog.tsx, line 54 at r1](https://reviewable.io/reviews/certusone/wormhole/866#-MwEBNm19gRNaMKs2FxV:-MwdzG2N76VI8joDcUj7:b-3yl7v0) ([raw file](https://github.com/certusone/wormhole/blob/5e607efcc1e919b0570c7d17271b3ae22c1c372b/bridge_ui/src/components/TerraConnectWalletDialog.tsx#L54)):*
<details><summary><i>Previously, kev1n-peters wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OK, Still not using useMemo, but we can revisit
___
*[bridge_ui/src/contexts/TerraWalletContext.tsx, line 17 at r1](https://reviewable.io/reviews/certusone/wormhole/866#-MwECdBnEZ-VhkTARdbP:-MwdyzzAAr--DSvejcFs:b644kez) ([raw file](https://github.com/certusone/wormhole/blob/5e607efcc1e919b0570c7d17271b3ae22c1c372b/bridge_ui/src/contexts/TerraWalletContext.tsx#L17)):*
<details><summary><i>Previously, kev1n-peters wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OK, this works in local


<!-- Sent from Reviewable.io -->

2022-02-24 04:52 UTC, merged