Add unit-test for governance
certusone/wormhole pull request #867
Opened 2022-02-16 16:53 UTC by claudijd

This adds a unit-test for default behavior governance component of vaa.  This is a pretty simple component, so the unit-testing is mostly verifying our defaults don't shift and helps explain how to interact with the lib.  In the future, if this lib adds more functionality, we can lock in more behavior expectations.

2022-02-16 16:59 UTC, SEJeff requested changes
Please run gofmt on this as your formatting for the conditionals is super weird. Hopefully you won't mind if I convert this to [testify later](https://github.com/stretchr/testify) unless you'd be willing to do it now.

The assertions (when the tests fail) are infinitely more developer friendly.

```
if gotVersion != wantVersion {
        t.Errorf("got %q, wanted %q", gotVersion, wantVersion)
}
```
when using testify becomes:

```
assert.Equal(t, gotVersion, wantVersion)
```

2022-02-16 22:09 UTC, leoluk requested changes
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/867)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @claudijd and @leoluk)

___
*[node/pkg/vaa/governance_test.go, line 19 at r1](https://reviewable.io/reviews/certusone/wormhole/867#-Mw3_6sOCxWuMWcZdrZH:-Mw3_6sOCxWuMWcZdrZI:b48mpsp) ([raw file](https://github.com/certusone/wormhole/blob/6ef717284c8288e2c4447ee2d57205849e256056/node/pkg/vaa/governance_test.go#L19)):*
> ```Go
> 	assert.Equal(t, vaa.GuardianSetIndex, uint32(1))
> 	assert.Nil(t, vaa.Signatures)
> 	assert.Equal(t, vaa.Timestamp, time.Unix(0, 0))
> ```

Presumably this will be prettier with a testify struct comparison?



_Code quote:_
```Go
	assert.Equal(t, vaa.Version, uint8(1))
	assert.Equal(t, vaa.GuardianSetIndex, uint32(1))
	assert.Nil(t, vaa.Signatures)
	assert.Equal(t, vaa.Timestamp, time.Unix(0, 0))
	assert.Equal(t, vaa.Timestamp, time.Unix(0, 0))
	assert.Equal(t, vaa.Nonce, uint32(1))
	assert.Equal(t, vaa.Sequence, uint64(1))
	assert.Equal(t, vaa.ConsistencyLevel, uint8(32))
	assert.Equal(t, vaa.ConsistencyLevel, uint8(32))
	assert.Equal(t, vaa.EmitterChain, ChainIDSolana)
	assert.Equal(t, vaa.EmitterAddress, Address{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4})
	assert.Equal(t, string(vaa.Payload), "aaaaaa")
```
___
*[node/pkg/vaa/governance_test.go, line 28 at r1](https://reviewable.io/reviews/certusone/wormhole/867#-Mw3_3Yp5-8zca-6mnOp:-Mw3_3Yp5-8zca-6mnOq:b-88s9hw) ([raw file](https://github.com/certusone/wormhole/blob/6ef717284c8288e2c4447ee2d57205849e256056/node/pkg/vaa/governance_test.go#L28)):*
> ```Go
> 	assert.Equal(t, vaa.EmitterAddress, Address{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4})
> 	assert.Equal(t, string(vaa.Payload), "aaaaaa")
> }              
> ```

Trailing spaces


<!-- Sent from Reviewable.io -->

2022-02-21 14:01 UTC, claudijd reviewed
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/867)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @leoluk)

___
*[node/pkg/vaa/governance_test.go, line 19 at r1](https://reviewable.io/reviews/certusone/wormhole/867#-Mw3_6sOCxWuMWcZdrZH:-MwR_8YREZAa0QI1sW9y:b-zfekv6) ([raw file](https://github.com/certusone/wormhole/blob/6ef717284c8288e2c4447ee2d57205849e256056/node/pkg/vaa/governance_test.go#L19)):*
<details><summary><i>Previously, leoluk (Leopold Schabel) wrote…</i></summary><blockquote>

Presumably this will be prettier with a testify struct comparison?
</blockquote></details>

The best I understand it, a struct table comparison would make more sense if the items being tested were all of the same type.  I'm unsure how to specify this in a context where I'm verifying a variety of types outside of this format.
 
___
*[node/pkg/vaa/governance_test.go, line 28 at r1](https://reviewable.io/reviews/certusone/wormhole/867#-Mw3_3Yp5-8zca-6mnOp:-MwR_2u58fWS7YPMevP4:b-896fix) ([raw file](https://github.com/certusone/wormhole/blob/6ef717284c8288e2c4447ee2d57205849e256056/node/pkg/vaa/governance_test.go#L28)):*
<details><summary><i>Previously, leoluk (Leopold Schabel) wrote…</i></summary><blockquote>

Trailing spaces
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-21 14:50 UTC, leoluk requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/867)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @claudijd and @leoluk)

___
*[node/pkg/vaa/governance_test.go, line 19 at r1](https://reviewable.io/reviews/certusone/wormhole/867#-Mw3_6sOCxWuMWcZdrZH:-MwRkhnf3sC2LNL6SBBy:bug2v5t) ([raw file](https://github.com/certusone/wormhole/blob/6ef717284c8288e2c4447ee2d57205849e256056/node/pkg/vaa/governance_test.go#L19)):*
<details><summary><i>Previously, claudijd (Jonathan Claudius) wrote…</i></summary><blockquote>

The best I understand it, a struct table comparison would make more sense if the items being tested were all of the same type.  I'm unsure how to specify this in a context where I'm verifying a variety of types outside of this format.
 
</blockquote></details>

Can't you just compare to a struct literal vs. each field individually?


<!-- Sent from Reviewable.io -->

2022-02-21 21:51 UTC, claudijd reviewed
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/867)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @leoluk)

___
*[node/pkg/vaa/governance_test.go, line 19 at r1](https://reviewable.io/reviews/certusone/wormhole/867#-Mw3_6sOCxWuMWcZdrZH:-MwTG3wh8vnZnBJo6Bte:b-plkfwn) ([raw file](https://github.com/certusone/wormhole/blob/6ef717284c8288e2c4447ee2d57205849e256056/node/pkg/vaa/governance_test.go#L19)):*
<details><summary><i>Previously, leoluk (Leopold Schabel) wrote…</i></summary><blockquote>

Can't you just compare to a struct literal vs. each field individually?
</blockquote></details>

I worked with Evan to figure this out, nice call, now fixed!


<!-- Sent from Reviewable.io -->

2022-02-21 22:01 UTC, evan-gray approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/867)* status: all files reviewed, 1 unresolved discussion (waiting on @leoluk)



<!-- Sent from Reviewable.io -->

2022-02-21 22:12 UTC, evan-gray approved these changes
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/867)* status: all files reviewed, 1 unresolved discussion (waiting on @leoluk)



<!-- Sent from Reviewable.io -->

2022-02-21 22:13 UTC, evan-gray approved these changes
> Dismissed @leoluk from a discussion.
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/867)* status: all files reviewed, 1 unresolved discussion (waiting on @leoluk)



<!-- Sent from Reviewable.io -->

2022-02-21 22:14 UTC, evan-gray approved these changes
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/867)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @leoluk)



<!-- Sent from Reviewable.io -->

2022-02-21 22:18 UTC, kcsongor approved these changes

2022-02-21 22:23 UTC, merged