Move type checking up for chainID
certusone/wormhole pull request #868
Opened 2022-02-16 19:27 UTC by claudijd

This moved up the chainID parsing logic to the beginning of the function and essentially guards against upper and lower bounds of uint32.

2022-02-16 19:56 UTC, SEJeff requested changes
When making changes to something like this, can you write tests to cover it first and then make the changes please? Keeps us all honest :)

2022-02-16 22:11 UTC, leoluk reviewed
It's argument parsing for a debug CLI utility, do we really need unit tests for this?

> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/868#-:-Mw3_VltC1fZkT_ayUAx:bsx2dv3)* status: 0 of 1 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-02-21 14:04 UTC, claudijd reviewed
My main limiting factor here is mostly understanding how to mock/test the cobra components, though I'd totally love having a pattern here we could replicate across the CLI utils.

> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/868#-:-MwR_piT6sonLga8up_x:bvz80lj)* status: 0 of 1 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-02-21 14:23 UTC, leoluk reviewed
These CLI utils are for debugging, we can write tests for those once we have tests for everything else! :D

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/certusone/wormhole/868#-:-MwRe1ml0zZxWfGG02Te:b-gms554)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @claudijd)



<!-- Sent from Reviewable.io -->

2022-03-08 17:40 UTC, closed without merging